export { default as TestMissed } from './TestMissed';
export { default as TestSubmiited } from './TestSubmiited';
export { default as AppNewsUpdate } from './TestCard';
export { default as UpcomingTest } from './UpcomingTest';
export { default as MutipleCheck } from './MultipleCheck';
export { default as TodayTest } from './TodayTest';
export { default as SingleCheck } from './SingleCheck';
export { default as ResultMutipleCheck } from './ResultMultipleCheck';
export { default as ResultSingleCheck } from './ResultSingleCheck';
